"""Assemble Elite for the PicoMite: a library and a program.

  Bas/elite/src/*.bas      hand-written, concatenated in filename order (00_, 10_, ...)
  Bas/elite/data/ships.bas generated by blueprints.py, all DATA

The output is two files, because one program cannot be more than MAX_PROG_SIZE
(144 KB on the PicoComputer) and Elite is heading past that:

  Bas/elite/elite_lib.bas  the declarations - every CONST and DIM, plus the ship
                           blueprint DATA.  Installed as the library.
  Bas/elite/elite.bas      the code.  Its first statement is LIBRARY LOAD, so the
                           program installs its own library on first run and does
                           nothing on every run after that.

The split follows a seam that was already there: 00_main.bas is nothing but
declarations and ships.bas is nothing but DATA, so neither holds a statement that
has to run in a particular order.  A library initialises itself before the
program's first line, so the CONSTs and DIMs are in place before any code runs,
and RESTORE reaches a label in the library from the program because subroutine,
function and label names are shared across the two halves.

The library also carries OPTION LOCAL VARIABLES, which must precede every DIM
anywhere - and the library's top level is the first thing that runs.  It splits a
fixed pool of 736 variable slots between locals and globals; the default leaves
only 480 globals and Elite declares 374 of them.

Order matters only in that the main program flow must come first and END before the SUBs,
and DATA blocks must follow.  Keep the numeric prefixes.

The assembled program is stripped of comments and indentation before it is written.
The sources are the readable copy; elite.bas is what has to fit in the PicoMite program
memory, and the comments are more than half of it.

Usage:  python build.py            assemble
        python build.py --full     assemble without stripping, for reading
        python build.py --check    assemble and report anything that looks illegal in MMBasic
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "..", "elite", "src"))
DATA = os.path.normpath(os.path.join(HERE, "..", "elite", "data", "ships.bas"))
TOKENS = os.path.normpath(os.path.join(HERE, "..", "elite", "data", "tokens.bas"))
OUT = os.path.normpath(os.path.join(HERE, "..", "elite", "elite.bas"))
OUTLIB = os.path.normpath(os.path.join(HERE, "..", "elite", "elite_lib.bas"))

# Where the library is looked for at run time, and how the variable pool is
# split.  128 locals leaves 608 globals; Elite declares 374 and no call chain
# comes near 128 locals deep.
# The library is looked for beside the program rather than in the root of a
# particular drive, so the two files can live anywhere as long as they live
# together.  MM.INFO(PATH) is the directory the running program was loaded
# from, with its trailing slash.
LIBNAME = "elite_lib.bas"
LOCALVARS = 128

# The declarations live here, and nothing else does.
LIB_SOURCES = ("00_main.bas",)

# A library runs its top level in front of EVERY program, not just this one, so
# it must not contain anything that only makes sense for Elite.  OPTION CACHE SUB
# names two of Elite's own SUBs, and with it in the library no other program will
# even start: 'Sub/function not found'.  Only the options that MUST precede a DIM
# stay behind - the variable split and the array base - and the rest move to the
# program, where they belong.
LIB_OPTIONS = ("OPTION BASE",)

# These configure the trace cache, and they belong in the program head
# whatever shape the line is.  The size depends on the machine now, so the
# statement can be the tail of an IF rather than the start of its line, and
# a mover that only recognised lines beginning with OPTION would carry the
# statement away and leave the IF behind.
PROG_OPTIONS = ("OPTION TRACECACHE", "OPTION CACHE")
NL = chr(10)

# Two lists, because the two cases differ.  A keyword or a no-argument
# builtin - one usable without parentheses - cannot be a variable or a
# parameter name: it silently breaks the enclosing definition.  A builtin
# that REQUIRES parentheses is harmless as a variable name (a variable
# called val or dir is fine) but still cannot be the name of a SUB or
# FUNCTION, which MMBasic rejects with "Invalid identifier".
RESERVED = set("""
pos timer pi date time day name scroll word as min max step to then else next loop until while wend
for do if endif end sub function local dim const global static option print input line read data restore
mode font colour color cls box circle rbox text pixel arc polygon triangle blit sprite framebuffer
math play pause inkey key keydown asc chr str hex oct bin space
error on off gosub goto return select case exit erase peek poke var save load run new list edit
rnd mm epoch cursor settick
""".split())

# Everything above, plus the parenthesised builtins, for SUB/FUNCTION names.
RESERVED_NAMES = RESERVED | set("""
distance choice field trim eof lof loc dir cwd bound val ln log exp sin cos tan sqr abs int fix sgn
instr mid val len tab atn asin acos deg rad pin port pwm sound tone left right chr asc str
""".split())

DECL = re.compile(r"^\s*(?:DIM|LOCAL|CONST|STATIC)\s+(.*)$", re.I)
SUBDEF = re.compile(r"^\s*(SUB|FUNCTION)\s+([A-Za-z_][A-Za-z0-9_]*)", re.I)
PARAMS = re.compile(r"^\s*(?:SUB|FUNCTION)\s+[A-Za-z_][A-Za-z0-9_$%!]*\s*\((.*?)\)", re.I)


def base_name(tok):
    """Strip a type suffix and any array parentheses from a declared name."""
    tok = tok.strip()
    tok = re.split(r"[(=]", tok, 1)[0].strip()
    return tok.rstrip("$%!").lower()


def declared_names(text):
    """Every name introduced by DIM / LOCAL / CONST, with its line number."""
    out = []
    for i, ln in enumerate(text.splitlines(), 1):
        code = ln.split("'")[0]
        m = DECL.match(code)
        if not m:
            continue
        body = m.group(1)
        body = re.sub(r"^\s*(INTEGER|FLOAT|STRING)\s+", "", body, flags=re.I)
        depth, cur, items = 0, "", []
        for ch in body:                      # split on commas outside parentheses
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            if ch == "," and depth == 0:
                items.append(cur)
                cur = ""
            else:
                cur += ch
        items.append(cur)
        for it in items:
            it = re.sub(r"\s+AS\s+\w+", "", it, flags=re.I)
            n = base_name(it)
            if n:
                out.append((n, i, ln.strip()))
    return out


STRLEN = re.compile(r"\b([A-Za-z_][A-Za-z0-9_.]*\$)\s*(?:\([^)]*\))?\s+LENGTH\s+(\d+)", re.I)
# name$ = "..." where the literal is the whole of the right hand side
STRASSIGN = re.compile(r"([A-Za-z_][A-Za-z0-9_.]*\$)\s*(?:\([^)]*\))?\s*=\s*\"([^\"]*)\"\s*(?=:|$)", re.I)


def code_of(ln):
    """The line with any trailing comment removed, minding quoted strings."""
    q = False
    for i, ch in enumerate(ln):
        if ch == chr(34):
            q = not q
        elif ch == chr(39) and not q:
            return ln[:i]
    return ln


def check(text):
    problems = []
    lines = text.splitlines()

    # reserved words used as names
    for n, i, ln in declared_names(text):
        if n in RESERVED:
            problems.append("line %d: '%s' is a reserved word: %s" % (i, n, ln))

    # A reserved word used as a SUB/FUNCTION parameter breaks the whole
    # definition, and MMBasic then reports "Variable name" at the CALL site,
    # which is nowhere near the real fault.  Worth catching here.
    for i, ln in enumerate(lines, 1):
        m = PARAMS.match(ln.split("'")[0])
        if not m:
            continue
        for prm in m.group(1).split(","):
            prm = re.sub(r"\s+AS\s+\w+", "", prm, flags=re.I)
            nm = base_name(prm)
            if nm in RESERVED:
                problems.append("line %d: parameter '%s' is a reserved word "
                                "(the caller will fail with 'Variable name'): %s" % (i, nm, ln.strip()))

    # duplicate global declarations (suffix-insensitive); LOCALs are per-SUB so track scope
    scope, seen = "(main)", {}
    for i, ln in enumerate(lines, 1):
        code = ln.split("'")[0]
        m = SUBDEF.match(code)
        if m:
            scope = m.group(2)
            continue
        if re.match(r"^\s*END\s+(SUB|FUNCTION)", code, re.I):
            scope = "(main)"
            continue
        m = DECL.match(code)
        if not m:
            continue
        is_local = code.strip().upper().startswith("LOCAL")
        key_scope = scope if is_local else "(global)"
        for n, _, _ in declared_names(ln):
            key = (key_scope, n)
            if key in seen:
                problems.append("line %d: '%s' already declared in %s at line %d" % (i, n, key_scope, seen[key]))
            else:
                seen[key] = i

    # A SUB or FUNCTION whose own name is a builtin - MMBasic rejects the
    # definition with "Invalid identifier", which at least points at the
    # right line, unlike the parameter case.
    for i, ln in enumerate(lines, 1):
        m = SUBDEF.match(ln.split("'")[0])
        if m and m.group(2).lower().rstrip("$%!") in RESERVED_NAMES:
            problems.append("line %d: '%s' is a reserved word or builtin: %s"
                            % (i, m.group(2), ln.strip()))

    # Two definitions of the same name: MMBasic reports "Duplicate name" at
    # the second one, which is clear enough, but the build should not get
    # that far.
    seen_subs = {}
    for i, ln in enumerate(lines, 1):
        m = SUBDEF.match(ln.split("'")[0])
        if not m:
            continue
        nm = m.group(2).lower().rstrip("$%!")
        if nm in seen_subs:
            problems.append("line %d: '%s' is already defined at line %d"
                            % (i, m.group(2), seen_subs[nm]))
        else:
            seen_subs[nm] = i

    # SUB/FUNCTION name colliding with a variable name
    subs = {m.group(2).lower().rstrip("$%!") for m in (SUBDEF.match(l.split("'")[0]) for l in lines) if m}
    for n, i, ln in declared_names(text):
        if n in subs:
            problems.append("line %d: '%s' is also a SUB/FUNCTION name: %s" % (i, n, ln))

    # Unbalanced block keywords.  Keywords can appear anywhere on a line
    # (single-line FOR ... : NEXT, statements after a colon), so walk the
    # words rather than matching the start of the line, and skip string
    # literals as well as comments.  EXIT FOR / EXIT DO are not closers.
    depth = {"SUB": 0, "FUNCTION": 0, "FOR": 0, "DO": 0, "SELECT": 0}
    OPENERS = {"FOR": "FOR", "DO": "DO", "SUB": "SUB", "FUNCTION": "FUNCTION", "SELECT": "SELECT"}
    CLOSERS = {"NEXT": "FOR", "LOOP": "DO"}
    for i, ln in enumerate(lines, 1):
        c = re.sub(r'"[^"]*"', '""', ln.split("'")[0]).upper()
        words = re.findall(r"[A-Z_]+", c)
        for j, w in enumerate(words):
            prev = words[j - 1] if j else ""
            if w in CLOSERS and prev != "EXIT":
                depth[CLOSERS[w]] -= 1
            elif w in OPENERS and prev not in ("END", "EXIT"):
                # A SUB or FUNCTION definition is always the first word of its
                # line; the word also appears inside OPTION CACHE SUB and in
                # EXIT SUB, neither of which opens a block.  FOR, DO and
                # SELECT can legitimately start a statement mid-line.
                if w in ("SUB", "FUNCTION") and j != 0:
                    continue
                # FOR also appears in OPEN ... FOR INPUT/OUTPUT/APPEND, which
                # opens a file rather than a loop.  A loop header always has a
                # TO after it.
                if w == "FOR" and "TO" not in words[j + 1:]:
                    continue
                depth[OPENERS[w]] += 1
            elif prev == "END" and w in depth:
                depth[w] -= 1
        for k, v in depth.items():
            if v < 0:
                problems.append("line %d: more closers than openers for %s: %s" % (i, k, ln.strip()))
                depth[k] = 0
    for k, v in depth.items():
        if v:
            problems.append("unclosed %s block(s): %d" % (k, v))

    # string literals that will not fit the variable they are assigned to.
    # MMBasic range-checks the assignment whatever LENGTH does about the
    # allocation, so an over-long caption is a run-time "String too long"
    # from wherever it happens to be reached - which in a demo can be
    # minutes in.  Only whole-literal assignments are checked, because
    # anything with a concatenation in it cannot be measured from here.
    sized = {}
    for i, ln in enumerate(lines, 1):
        for m in STRLEN.finditer(code_of(ln)):
            sized[m.group(1).lower()] = int(m.group(2))
    for i, ln in enumerate(lines, 1):
        for m in STRASSIGN.finditer(code_of(ln)):
            n = sized.get(m.group(1).lower())
            if n is not None and len(m.group(2)) > n:
                problems.append("line %d: %s is LENGTH %d but is given %d characters: \"%s\""
                                % (i, m.group(1), n, len(m.group(2)), m.group(2)))

    # lines longer than the console/editor is happy with
    for i, ln in enumerate(lines, 1):
        if len(ln) > 240:
            problems.append("line %d: %d characters (keep under 240)" % (i, len(ln)))
    return problems


# The PicoMite keeps the program tokenised in flash and there is not much room;
# a comment costs the same as code.  Past this, AUTOSAVE stops with "Not enough
# memory", but the rest of the transfer is echoed at the prompt and scrolls that
# away - the reliable sign is a missing "Saved nnn bytes" report.  AUTOSAVE C
# and LOAD ,C crunch on the way in and avoid the whole problem.
PROGRAM_LIMIT = 130000


def strip(text):
    """Drop comments, blank lines and indentation, keeping everything else verbatim.

    A trailing comment is only removed from a line with no string literal on it:
    telling an apostrophe that opens a comment from one inside a string needs a real
    tokeniser, and the lines with both are too few to be worth one.
    """
    out = []
    for line in text.split(chr(10)):
        t = line.strip()
        if not t or t.startswith(chr(39)) or t[:4].upper() == 'REM ':
            continue
        if chr(34) not in t and chr(39) in t:
            t = t.split(chr(39), 1)[0].rstrip()
            if not t:
                continue
        out.append(t)
    return chr(10).join(out) + chr(10)


def check_split(lib, prog):
    """Rules that only exist because the program is in two halves."""
    problems = []

    # The trace cache compiles a subroutine against the program it was
    # prepared from.  Its options, and every subroutine they name, belong in
    # the main program; neither may be in the library.
    for i, ln in enumerate(lib.split(NL), 1):
        t = ln.strip().upper()
        if not t.startswith(chr(39)) and any(k in t for k in PROG_OPTIONS):
            problems.append("library line %d: %s belongs in the main program"
                            % (i, ln.strip()))

    cached = []
    for ln in prog.split(NL):
        t = ln.strip()
        if t.upper().startswith("OPTION CACHE SUB"):
            for nm in t[16:].split(","):
                nm = nm.strip().rstrip("$%!")
                if nm:
                    cached.append(nm)
    libsubs = set()
    for ln in lib.split(NL):
        m = SUBDEF.match(ln.split(chr(39))[0])
        if m:
            libsubs.add(m.group(2).lower().rstrip("$%!"))
    progsubs = set()
    for ln in prog.split(NL):
        m = SUBDEF.match(ln.split(chr(39))[0])
        if m:
            progsubs.add(m.group(2).lower().rstrip("$%!"))
    for nm in cached:
        if nm.lower() in libsubs:
            problems.append("OPTION CACHE SUB names %s, which is in the library" % nm)
        elif nm.lower() not in progsubs:
            problems.append("OPTION CACHE SUB names %s, which is defined nowhere" % nm)

    # A library is run in front of every program, so an END in it would stop
    # the run before the program started.
    for i, ln in enumerate(lib.split(NL), 1):
        t = ln.strip().upper()
        if t == "END" or t.startswith("END "):
            if not t.startswith("END SUB") and not t.startswith("END FUNCTION"):
                problems.append("library line %d: END would stop the run before the "
                                "program started: %s" % (i, ln.strip()))
    return problems


def main():
    full_mode = "--full" in sys.argv
    libparts, progparts, libnames, prognames = [], [], [], []
    for fn in sorted(os.listdir(SRC)):
        if not fn.endswith(".bas"):
            continue
        text = open(os.path.join(SRC, fn), encoding="utf-8").read().rstrip(NL)
        if fn in LIB_SOURCES:
            libparts.append(text)
            libnames.append(fn)
        else:
            progparts.append(text)
            prognames.append(fn)

    ships = open(DATA, encoding="utf-8").read().rstrip(NL)
    libnames.append("ships.bas")
    libnames.append("tokens.bas")
    bar = "' " + "=" * 70

    libhead = [
        "' Elite: the declarations and the ship data, installed as the library.",
        "' There must be no END in here - the interpreter runs the whole library at",
        "' RUN, and an END would stop the run before the program ever started.",
        "' OPTION LOCAL VARIABLES has to come before any DIM anywhere, and the",
        "' library runs before the program, so this is the only place it can go.",
        "OPTION LOCAL VARIABLES %d" % LOCALVARS,
        "",
    ]
    # Split the OPTION lines: what must run before a DIM stays in the library,
    # everything else is moved to the head of the program.
    moved = []
    kept = []
    for part in libparts:
        outlines = []
        for ln in part.split(NL):
            t = ln.strip()
            u = t.upper()
            move = u.startswith("OPTION ") and not any(
                    u.startswith(k) for k in LIB_OPTIONS)
            if not move and not t.startswith(chr(39)):
                move = any(k in u for k in PROG_OPTIONS)
            if move:
                moved.append(t)
                continue
            outlines.append(ln)
        kept.append(NL.join(outlines))
    libparts = kept

    lib = NL.join(libhead) + NL + (NL + NL).join(libparts) + NL + NL
    lib += bar + NL
    lib += "' ship blueprint data (generated by elite_tools/blueprints.py)" + NL
    lib += bar + NL + ships + NL + NL
    lib += bar + NL
    lib += "' extended text tokens (generated by elite_tools/tokens.py)" + NL
    lib += bar + NL + open(TOKENS, encoding="utf-8").read().rstrip(NL) + NL

    proghead = [
        "' Elite for the PicoMite.  The declarations and the ship data live in",
        "' " + os.path.basename(OUTLIB) + ", which this installs as the library on",
        "' its first run; after that the command finds the library already matches",
        "' and does nothing.  It must be the first statement in the program.",
        "LIBRARY LOAD MM.INFO(PATH) + " + chr(34) + LIBNAME + chr(34),
        "",
    ]
    if moved:
        proghead.append("' Moved out of the declarations: a library runs in front of every")
        proghead.append("' program, so anything naming this one's SUBs has to live here.")
        proghead.extend(moved)
        proghead.append("")
    prog = NL.join(proghead) + NL + (NL + NL).join(progparts) + NL

    # Checked together: the two halves share one namespace at run time, so a
    # duplicate or a collision across the seam is as fatal as one inside a file.
    problems = check(lib + NL + prog) + check_split(lib, prog)
    fulllen = len(lib) + len(prog)
    if not full_mode:
        lib = "' Elite library, built by elite_tools/build.py - read src/ instead." + NL + strip(lib)
        prog = ("' Elite for the PicoMite, built by elite_tools/build.py from src/*.bas." + NL
                + "' Comments and indentation are stripped to fit program memory - read src/." + NL
                + strip(prog))
    open(OUTLIB, "w", newline=NL, encoding="utf-8").write(lib)
    open(OUT, "w", newline=NL, encoding="utf-8").write(prog)

    print("built %s: %d lines, %d bytes from %s"
          % (OUTLIB, lib.count(NL), len(lib), ", ".join(libnames)))
    print("built %s: %d lines, %d bytes from %s"
          % (OUT, prog.count(NL), len(prog), ", ".join(prognames)))
    print("      %d bytes in all (%d before stripping); each half must fit %d"
          % (len(lib) + len(prog), fulllen, PROGRAM_LIMIT))
    for what, n in ((OUTLIB, len(lib)), (OUT, len(prog))):
        if n > PROGRAM_LIMIT:
            print("  ** %s is %d bytes, over the %d the PicoMite will hold **" % (what, n, PROGRAM_LIMIT))
    if problems:
        print(NL + "%d possible problems:" % len(problems))
        for p in problems:
            print("  " + p)
    else:
        print("checks clean")
    return 1 if ("--check" in sys.argv and problems) else 0

if __name__ == "__main__":
    sys.exit(main())
