"""The 6502 Second Processor version's extra ships.

The cassette game has twelve designs.  The 6502 Second Processor version has
thirty, and the ones that actually turn up in flight are added here: the pack
hunters a pirate group is drawn from, the heavier ships a lone bounty hunter
flies, the big traders, and the rest of the rubble.  Their blueprints are in
the same beebasm format as the cassette's, so blueprints.py's parser and
polygon builder do all of the work; this picks the ones we want out of the
6502SP source and appends them to data/ships.bas.

Left out on purpose, and why:

  Shuttle, Transporter   station traffic - they are spawned by the station,
                         which is a separate piece of behaviour
  Constrictor            the target of mission 1, which we do not have
  Dodo                   the second space station, likewise
  Elite logo             not a ship
  Moray                  famously unreachable: the 6502SP picks a lone bounty
                         hunter from types 24 to 27 and the Moray is 28, so no
                         code in the game ever spawns one

Usage:  python extras.py            (reads cache/6502sp-source.asm)
"""
import os, sys
import blueprints as bp

HERE = os.path.dirname(os.path.abspath(__file__))
ASM = os.path.join(HERE, "cache", "6502sp-source.asm")
SHIPS = os.path.normpath(os.path.join(HERE, "..", "elite", "data", "ships.bas"))

# label in the 6502SP source -> the name the game shows
EXTRAS = [
    ("COUGAR", "Cougar"),
    ("KRAIT", "Krait"),
    ("ADDER", "Adder"),
    ("GECKO", "Gecko"),
    ("COBRA_MK_1", "Cobra Mk I"),
    ("WORM", "Worm"),
    ("ASP_MK_2", "Asp Mk II"),
    ("FER_DE_LANCE", "Fer-de-Lance"),
    ("BOA", "Boa"),
    ("ANACONDA", "Anaconda"),
    ("BOULDER", "Boulder"),
    ("SPLINTER", "Splinter"),
    ("ROCK_HERMIT", "Rock hermit"),
]

# Everything the scratch mesh buffers in 00_main.bas have to hold.
LIMITS = {"vertices": 50, "polygons": 32, "normals": 16, "face vertices": 160}


def emit(sh, disp):
    st = sh["stats"]
    polys = sh["polys"]
    nfv = sum(len(p[0]) for p in polys)
    out = ["dat_%s:" % sh["name"].lower()]
    out.append('DATA "%s", %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d' % (
        disp, len(sh["verts"]), len(polys), nfv, len(sh["faces"]), sh["nv0"],
        st["canisters"], st["area"], st["bounty10"], st["visdist"], st["energy"],
        st["speed"], st["laser"], st["missiles"], st["gun_vertex"], st["explosion"]))
    vs = sh["verts"]
    for k in range(0, len(vs), 6):
        out.append("DATA " + ", ".join("%g,%g,%g" % tuple(v) for v in vs[k:k + 6]))
    out.append("DATA " + ",".join(str(len(p[0])) for p in polys))
    out.append("DATA " + ",".join(str(p[1]) for p in polys))
    ns = sh["faces"]
    for k in range(0, len(ns), 6):
        out.append("DATA " + ", ".join("%d,%d,%d" % tuple(n) for n in ns[k:k + 6]))
    for p in polys:
        out.append("DATA " + ",".join(str(i) for i in p[0]))
    out.append("")
    return out, (len(sh["verts"]), len(polys), len(sh["faces"]), nfv)


def main():
    ships = bp.parse_asm(ASM)
    text = open(SHIPS, encoding="ascii").read()
    marker = "' ---- the 6502 Second Processor version's extra ships"
    head = text[:text.index(marker)] if marker in text else (
        text if text.endswith(chr(10)) else text + chr(10))

    out = [marker, "' generated by elite_tools/extras.py from the 6502SP source", ""]
    print("%-16s %4s %4s %4s %4s" % ("ship", "nv", "poly", "nf", "nfv"))
    worst = [0, 0, 0, 0]
    for label, disp in EXTRAS:
        if label not in ships:
            raise SystemExit("no blueprint called %s in the source" % label)
        sh = bp.build(ships[label])
        block, sizes = emit(sh, disp)
        out += block
        worst = [max(a, b) for a, b in zip(worst, sizes)]
        print("%-16s %4d %4d %4d %4d" % ((disp,) + sizes))
        for m in sh["notes"]:
            print("    note:", m)
    print()
    print("largest: %d vertices, %d polygons, %d normals, %d face vertices"
          % (worst[0], worst[1], worst[2], worst[3]))
    for name, got, lim in (("vertices", worst[0], LIMITS["vertices"]),
                           ("polygons", worst[1], LIMITS["polygons"]),
                           ("normals", worst[2], LIMITS["normals"]),
                           ("face vertices", worst[3], LIMITS["face vertices"])):
        if got > lim:
            raise SystemExit("%s: %d needed, the scratch buffer holds %d - "
                             "raise it in 00_main.bas" % (name, got, lim))
    open(SHIPS, "w", newline=chr(10), encoding="ascii").write(head + chr(10).join(out))
    print("appended %d ships to %s" % (len(EXTRAS), SHIPS))


if __name__ == "__main__":
    main()
