"""Extract the disc version's extended token table.

The cassette game's data screen stops at the planet's radius.  The disc version
adds a paragraph - "Lave is most famous for its vast rain forests and the Lave
tree grub" - built by expanding a token from a table of 256, where some tokens
choose at random between five alternatives and the random number generator has
been seeded from the system's own s1 and s2, so a given system always gets the
same description.

The table is TKN1 in the 6502 Second Processor source, and the encoding is
carried by the macros themselves rather than by the bytes they emit, so nothing
here has to decode 6502 data:

    ECHR 'x'        one literal character
    ETWO 'a','b'    a two-letter token - the two letters, literally
    ETOK n          print extended token n
    TOKN n          the same
    ERND n          print one of the five tokens the n'th random group names
    EJMP n          a control code: case, newline, the planet's name, and so on
    EQUB VE         end of this token

What comes out is one string per token with the literals in place and markers
left for the rest, so the PicoMite only has to walk a string:

    [n]     print token n
    [n?]    print a random choice from group n
    {n}     control code n

Usage:  python tokens.py            writes ../elite/data/tokens.bas
"""
import io, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ASM = os.path.join(HERE, "cache", "6502sp-source.asm")
OUT = os.path.normpath(os.path.join(HERE, "..", "elite", "data", "tokens.bas"))
TOKLEN = 160   # must match the LENGTH of tk$() in 00_main.bas
BS = chr(92)


def parse(path):
    src = io.open(path, encoding="latin-1").read().splitlines()
    start = next(i for i, l in enumerate(src) if l.strip() == ".TKN1")
    end = next(i for i, l in enumerate(src)
               if i > start and re.match("^[.][A-Z]", l.strip()) and "TKN1" not in l)
    tokens, cur = [], []
    for line in src[start + 1:end]:
        c = line.split(BS)[0].strip()
        if not c:
            continue
        op = c.split()[0]
        arg = c[len(op):].strip()
        if op == "EQUB" and arg == "VE":
            tokens.append("".join(cur))
            cur = []
        elif op == "ECHR":
            m = re.match(r"^" + chr(39) + r"(.)" + chr(39) + r"$", arg)
            if not m:
                raise SystemExit("odd ECHR: " + c)
            cur.append(m.group(1))
        elif op == "ETWO":
            m = re.match("^" + chr(39) + "(.)" + chr(39) + "[ ]*,[ ]*" + chr(39) + "(.)" + chr(39) + "$", arg)
            if not m:
                raise SystemExit("odd ETWO: " + c)
            cur.append(m.group(1) + m.group(2))
        elif op in ("ETOK", "TOKN"):
            cur.append("[" + arg + "]")
        elif op == "ERND":
            cur.append("[" + arg + "?]")
        elif op == "EJMP":
            cur.append("{" + arg + "}")
        else:
            raise SystemExit("unknown directive: " + c)
    return tokens


def groups(path):
    """MTIN: the base token each of the 38 random groups picks its five from."""
    src = io.open(path, encoding="latin-1").read().splitlines()
    start = next(i for i, l in enumerate(src) if l.strip() == ".MTIN")
    out = []
    for line in src[start + 1:]:
        c = line.split(BS)[0].strip()
        if not c:
            continue
        if not c.startswith("EQUB"):
            break
        out.append(int(c.split()[1]))
    return out


def digrams(path, n=32):
    """The two-letter tokens control code 18 makes its alien words out of.

    It reads from TKN2 + 2, which skips the newline pair at the start, and the
    offset it picks is an even number 0 to 62 - so only the first 32 pairs can
    ever come up, and the QQ16 table the source mentions is never reached."""
    src = io.open(path, encoding="latin-1").read().splitlines()
    i = next(k for k, l in enumerate(src) if l.strip() == ".TKN2")
    out = []
    for l in src[i + 1:i + 120]:
        out += re.findall("EQUS " + chr(34) + "(..)" + chr(34), l)
        if len(out) >= n:
            break
    return out[:n]


def basic_quote(t):
    """MMBasic has no escape for a quote inside a string literal, so a token
    containing one is split and rejoined with CHR$(34)."""
    parts = t.split(chr(34))
    lit = (chr(34) + ' + CHR$(34) + ' + chr(34)).join(parts)
    return chr(34) + lit + chr(34)


def main():
    tokens = parse(ASM)
    mtin = groups(ASM)
    print("%d tokens, %d random groups" % (len(tokens), len(mtin)))
    for n in (5, 16, 53, 96):
        print("  token %3d %s" % (n, repr(tokens[n])))

    out = ["' The disc version's extended token table, generated by",
           "' elite_tools/tokens.py from the 6502 Second Processor source.",
           "' Do not edit: regenerate it.",
           "'",
           "'   [n]   print token n        [n?]  a random one of group n",
           "'   {n}   control code n",
           "'",
           "' Token 5 is the whole of a system description:",
           "'   " + tokens[5],
           "",
           "dat_tokens:"]
    # An MMBasic string is at most 255 characters and a string array element is
    # whatever LENGTH says, so the four longest tokens cannot be stored.  All
    # four are mission briefings, for missions this port does not have, and
    # nothing reachable from a system description comes near the limit - the
    # longest of those is 30 characters.
    dropped = []
    for i, t in enumerate(tokens):
        if len(t) > TOKLEN:
            dropped.append((i, len(t)))
            t = ""
        out.append("DATA " + basic_quote(t))
    if dropped:
        print("  dropped (too long to hold in a string): " +
              ", ".join("%d at %d chars" % d for d in dropped))
    out.append("")
    out.append("' The two-letter tokens control code 18 builds alien words from.")
    out.append("dat_digrams:")
    dg = digrams(ASM)
    for k in range(0, len(dg), 16):
        out.append("DATA " + ",".join(chr(34) + d + chr(34) for d in dg[k:k + 16]))
    out.append("")
    out.append("' MTIN: the base token each random group chooses its five from.")
    out.append("dat_rndgroups:")
    for k in range(0, len(mtin), 16):
        out.append("DATA " + ",".join(str(v) for v in mtin[k:k + 16]))
    out.append("")
    text = chr(10).join(out)
    open(OUT, "w", newline=chr(10), encoding="ascii").write(text)
    print("wrote %s, %d bytes" % (OUT, len(text)))
    print("longest token kept: %d characters (tk$() needs LENGTH %d)"
          % (max(len(t) for t in tokens if len(t) <= TOKLEN), TOKLEN))


if __name__ == "__main__":
    main()
