/* mmcsub.h - the runtime a CSUB generated by mmb2csub.py compiles against.
 *
 * Two jobs, and the second one is the interesting one.
 *
 * 1. The generator (mmb2c) names its runtime helpers mm_something(). Every one
 *    this file defines is supported; every one it does not is a compile error
 *    that names itself. That IS the scope check - the C compiler enforces it,
 *    so no hand-written list of supported statements can drift out of date.
 *
 * 2. A transpiler emits ordinary C operators - `a * b` on doubles, `i += 1` in
 *    a FOR loop, `i <= limit` - in dozens of places, in statement emitters as
 *    well as expression ones. On Cortex-M0+ those become calls to __aeabi_
 *    helpers, and a CSUB links without libgcc, so each one would otherwise be
 *    an undefined reference. Rather than teach the generator to avoid every
 *    operator, this file supplies the helpers as shims that forward to the
 *    firmware's own routines through the CallTable. The arithmetic still runs
 *    in the firmware exactly as a hand-written CSUB's FAdd/FMul would; there is
 *    no second copy of soft-float in the blob and no libgcc anywhere.
 *
 *    This is the same trick as the memcpy/memset shims in PicoCFunctions.h: the
 *    compiler calls these by name, so the names have to exist.
 *
 *    None of them can recurse. Each body is an indirect call through a
 *    CallTable vector, which the compiler cannot fold back into the operator it
 *    came from. (Writing `return a + b;` here WOULD recurse - don't.)
 *
 * Requires firmware 6.03.02b8 or later for the L* and mem* slots.
 */
#ifndef MMCSUB_H
#define MMCSUB_H

#define CSUB_MEM_SHIMS /* we want the memcpy/memset/memmove symbols too */
#include "PicoCFunctions.h"

typedef long long MMINTEGER;
/* MMFLOAT is already double, from PicoCFunctions.h */

/* ------------------------------------------------------------------ *
 *  Fuzix runtime hooks that a CSUB has no use for
 * ------------------------------------------------------------------ */
/* temp-memory marking: a CSUB's temporaries are on the stack */
#define mm_mark() 0u
#define mm_release(m) ((void)(m))

/* ------------------------------------------------------------------ *
 *  Arithmetic the generator calls by name
 * ------------------------------------------------------------------ */
#define mm_idiv(a, b) LDiv((a), (b))  /* MMBasic \   */
#define mm_mod(a, b) LMod((a), (b))   /* MMBasic MOD */
#define mm_fdiv(a, b) FDiv((a), (b))  /* checked /   */
#define mm_toint(a) FloatToInt(a)     /* rounds, as MMBasic does */
#define mm_pow(a, b) Power((a), (b))  /* ^ */

/* ------------------------------------------------------------------ *
 *  Graphics with a CallTable slot
 * ------------------------------------------------------------------ */
/* DrawPixel takes a FULL RGB colour and packs it for whatever mode is
   active, so this is format- and version-independent. */
#define mm_pixel(x, y, c) DrawPixel((int)(x), (int)(y), (int)(c))

/* Deliberately absent: mm_map_get (the MAP() function). The colour map has no
   CallTable slot, and in a fixed mode its sixteen values are constants - so
   pass them in as an INTEGER array and index that instead. */

/* ------------------------------------------------------------------ *
 *  Maths functions with a CallTable slot
 * ------------------------------------------------------------------ */
#define mm_sin(a) Sine(a)
#define mm_cos(a) Cosine(a)
#define mm_sqr(a) Sqrt(a)
#define mm_atan2(a, b) Atan2((a), (b))

/* ------------------------------------------------------------------ *
 *  Compiler-emitted helpers, routed to the firmware's routines.
 *
 *  Deliberately absent: __aeabi_ldivmod and __aeabi_uldivmod. Their result
 *  convention (quotient in r0:r1, remainder in r2:r3) cannot be written in C,
 *  and the generator never needs them - it emits mm_idiv/mm_mod for MMBasic's
 *  \ and MOD. If one ever shows up as an undefined reference, that means raw
 *  64-bit / or % reached the output, and it should be fixed there rather than
 *  papered over here.
 * ------------------------------------------------------------------ */

/* --- double arithmetic --- */
double __aeabi_dadd(double a, double b) { return FAdd(a, b); }
double __aeabi_dsub(double a, double b) { return FSub(a, b); }
double __aeabi_dmul(double a, double b) { return FMul(a, b); }
double __aeabi_ddiv(double a, double b) { return FDiv(a, b); }

/* --- double comparison. The C-callable set; GCC uses these on M0+. --- */
int __aeabi_dcmpeq(double a, double b) { return FCmp(a, b) == 0; }
int __aeabi_dcmplt(double a, double b) { return FCmp(a, b) < 0; }
int __aeabi_dcmple(double a, double b) { return FCmp(a, b) <= 0; }
int __aeabi_dcmpge(double a, double b) { return FCmp(a, b) >= 0; }
int __aeabi_dcmpgt(double a, double b) { return FCmp(a, b) > 0; }
/* "unordered" - no NaNs reach here from MMBasic arithmetic, so 0 is right */
int __aeabi_dcmpun(double a, double b) { (void)a; (void)b; return 0; }

/* --- conversions --- */
double __aeabi_i2d(int a) { return IntToFloat((long long)a); }
double __aeabi_ui2d(unsigned a) { return IntToFloat((long long)a); }
double __aeabi_l2d(long long a) { return IntToFloat(a); }
double __aeabi_ul2d(unsigned long long a) { return IntToFloat((long long)a); }
/* d2*z truncate TOWARD ZERO - that is what a C cast means. FloatToInt rounds
   (x>=0 ? x+0.5 : x-0.5), which is MMBasic's conversion and what the generator
   spells mm_toint, so it is wrong here: round first, then step back toward zero
   if rounding overshot. The comparisons below go through the dcmp shims above,
   so nothing recurses. */
long long __aeabi_d2lz(double a)
{
    long long t = FloatToInt(a);
    if (a >= 0.0) {
        if (IntToFloat(t) > a)
            t -= 1;
    } else {
        if (IntToFloat(t) < a)
            t += 1;
    }
    return t;
}
int __aeabi_d2iz(double a) { return (int)__aeabi_d2lz(a); }

/* --- 64-bit integer helpers --- */
long long __aeabi_lmul(long long a, long long b) { return LMul(a, b); }
long long __aeabi_llsl(long long a, int n) { return LShl(a, n); }
long long __aeabi_lasr(long long a, int n) { return LAsr(a, n); }
unsigned long long __aeabi_llsr(unsigned long long a, int n) { return LLsr(a, n); }

/* --- 32-bit divide (no divider on M0+) --- */
int __aeabi_idiv(int a, int b) { return IDiv(a, b); }
unsigned __aeabi_uidiv(unsigned a, unsigned b) { return (unsigned)IDiv((int)a, (int)b); }

#endif /* MMCSUB_H */
