"""gen_csubtest.py - build the CSUB physics kernel and its test program.

Writes csub/exilestate.h (the layout of the state array, shared with the
BASIC), compiles csub/exilephys.c into a CSUB block with
user-tools/armcfgen.py, packs the tables the kernel reads into
out/phys/tables.bin, and assembles Bas/exile/physcsub.bas from
Bas/exile/physcsub_harness.bas, the state constants, the player's starting
values and the CSUB block.  The feed files are the ones gen_phystest.py
writes; run_phystest.py --prog physcsub.bas checks the result.

    python gen_csubtest.py exile-disassembly.txt
"""
import os
import subprocess
import sys

from exile6502 import load_listing
from exilegame import ACTIONS, OBJ
from gen_phystest import player_init

here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, 'out')
root = os.path.normpath(os.path.join(here, '..', '..'))

# the state array: one 64-bit element per name, in this order
STATE = ['x', 'xf', 'y', 'yf', 'vx', 'vy', 'flags', 'sprite', 'palette', 'energy', 'state', 'timer', 'touching',
         'frame', 'angle', 'facing', 'immob', 'timmob', 'rotvel', 'lying', 'aim', 'aimvel', 'aimflip',
         'jetok', 'inwater', 'tbcoll', 'surr', 'wedged', 'signs', 'windsign', 'reltx', 'relty', 'walkspd',
         'maxacc0', 'npcw0', 'firecool', 'watertile', 'jetlo', 'jethi', 'suithi', 'boostercol', 'suitcol',
         'typeflags', 'paldefault', 'crossx', 'crossy', 'kmask', 'feedmode', 'feedn', 'feedi',
         'feeda0', 'feedv0', 'feeda1', 'feedv1', 'feeda2', 'feedv2'] + \
        ['wl%d' % i for i in range(8)] + ['fault', 'faultarg'] + ['rnd%d' % i for i in range(4)] + \
        ['preang', 'premag', 'objcy', 'tileang', 'anyb', 'upright'] + ['kh%d' % i for i in range(39)]
STATE_SIZE = 128

# the packed tables: (C name, tables.bas label, size)
TABLES = [('OBPAT', 'ObstructionPatterns', 168), ('OBOFF', 'ObstructionPatternOffsets', 40),
          ('YOFF', 'TileObstructionYOffsets', 64), ('PAT', 'TileYOffsetAndPattern', 64),
          ('SPRF', 'TileSprites', 64), ('RTFLAGS', 'UpdateRoutineFlags', 20),
          ('SPRW', 'SpriteWidths', 125), ('SPRH', 'SpriteHeights', 125), ('HALFQ', 'AngleHalfQuadrants', 8),
          ('WATERVEL', 'WaterVelocities', 4), ('WLX', 'WaterRangeX', 4), ('WALKMAXANG', 'WalkMaxAngle', 7),
          ('WALKMAXACC', 'WalkMaxAccel', 7), ('WALKWEIGHT', 'WalkWeightShift', 7),
          ('WEAPONCOST', 'WeaponEnergyCost', 6), ('OBJFLAGS', 'ObjectFlags', 101),
          ('OBJPAL', 'ObjectPalettes', 101), ('NOREPEAT', None, 39)]


def read_tables_bas():
    """{label: [values]} from out/tables.bas."""
    tabs, cur = {}, None
    for line in open(os.path.join(out, 'tables.bas'), encoding='utf-8'):
        line = line.strip()
        if line.endswith(':') and ' ' not in line:
            cur = line[:-1]
            tabs[cur] = []
        elif line.lower().startswith('data ') and cur:
            tabs[cur] += [int(v) for v in line[5:].split(',')]
    return tabs


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return 2
    mem = load_listing(sys.argv[1])
    assert len(STATE) <= STATE_SIZE
    # the state layout, for C and for BASIC
    hdr = ["/* exilestate.h - generated by gen_csubtest.py: the state array's layout */"]
    consts = ["' the state array's layout, generated by gen_csubtest.py"]
    for i, n in enumerate(STATE):
        hdr.append("#define S_%s %d" % (n.upper(), i))
        consts.append("Const S_%s = %d" % (n.upper(), i))
    hdr.append("#define STATE_SIZE %d" % STATE_SIZE)
    off = 0
    tabs = read_tables_bas()
    tabs['NOREPEAT'] = [mem[0x121D + i] & 1 for i in range(len(ACTIONS))]
    packed = bytearray()
    for cname, label, size in TABLES:
        vals = tabs[label] if label else tabs['NOREPEAT']
        assert len(vals) >= size, (cname, len(vals), size)
        hdr.append("#define T_%s %d" % (cname, off))
        packed += bytes(vals[:size])
        off += size
    while len(packed) % 8:
        packed.append(0)
    hdr.append("#define TABLES_BYTES %d" % len(packed))
    cdir = os.path.join(here, 'csub')
    open(os.path.join(cdir, 'exilestate.h'), 'w', newline='\n').write("\n".join(hdr) + "\n")
    pdir = os.path.join(out, 'phys')
    os.makedirs(pdir, exist_ok=True)
    open(os.path.join(pdir, 'tables.bin'), 'wb').write(packed)
    print("tables.bin: %d bytes; state: %d of %d slots" % (len(packed), len(STATE), STATE_SIZE))

    # the CSUB block
    block = os.path.join(cdir, 'exile_csub.txt')
    cmd = [sys.executable, os.path.join(root, 'user-tools', 'armcfgen.py'), os.path.join(cdir, 'exilephys.c'),
           '--compile', '-n', 'ExileUpdate', '-e', 'exile_update', '-O', '2', '-I', cdir, '-o', block]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        print(r.stdout)
        print(r.stderr)
        return 1
    hexwords = sum(len(l.split()) for l in open(block) if l.strip() and not l.strip().startswith(("CSUB", "End", "'")))
    print("CSUB block: %d words (%d bytes of code)" % (hexwords, hexwords * 4))

    # the program
    harness = open(os.path.join(here, '..', 'exile', 'physcsub_harness.bas'), encoding='utf-8').read()
    init = "' the player's type flags, default palette, walking acceleration and weight shift\nObjectFlagsInit:\nData %d,%d,%d,%d\n" % (
        tabs['ObjectFlags'][0], tabs['ObjectPalettes'][0] & 0x7F, tabs['WalkMaxAccel'][0], tabs['WalkWeightShift'][0])
    marker = "' @@CONSTS@@ (gen_csubtest.py puts the state layout here)"
    assert marker in harness, "the harness needs the @@CONSTS@@ marker before Main"
    harness = harness.replace(marker, "\n".join(consts) + "\nConst TABLES_BYTES = %d" % len(packed))
    prog = harness.rstrip('\n') + "\n\n" + player_init(mem) + init + "\n" + open(block).read()
    dest = os.path.join(here, '..', 'exile', 'physcsub.bas')
    open(dest, 'w', newline='\r\n').write(prog)
    print("wrote", os.path.normpath(dest), "(%d lines)" % prog.count('\n'))
    return 0


if __name__ == '__main__':
    sys.exit(main())
