"""test_objects.py - put the object sheet on the PC3 and check it against a reference.

Writes Bas/exile/objview.bas, which loads out/exile_slot2.bmp into flash
slot 2 - the tail of the tileset with the object sheet below it, since the
library takes slot 3 - and blits sixty sprites and two of them in all four
orientations over a blue background with the key colour transparent, then
saves a screenshot; and writes ref_objects.png, the same picture made from
the BMP on this side.  The two must be identical.

    python test_objects.py            writes the program and the reference
"""
import json
import os
import struct
import sys

from gen_tiles import read_bmp4, save_png, BBC_RGB

here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, 'out')
SPACEMAN = (4, 0x3E)      # SPRITE_SPACESUIT_VERTICAL in the player's palette
IMP = (0x64, 0x51)        # SPRITE_IMP_WALKING_ONE in the red-magenta imp's palette


def main():
    entries = json.load(open(os.path.join(out, 'objects.json')))
    _, _, sheet = read_bmp4(os.path.join(out, 'exile_slot2.bmp'))

    # the selection the program makes: the first sixty distinct sprites, unflipped
    shown = []
    last = -1
    for e in entries:
        if e['flip'] == 0 and e['sprite'] != last and len(shown) < 60:
            shown.append(e)
            last = e['sprite']
    flips = {(e['sprite'], e['palette'], e['flip']): e for e in entries}

    # reference picture
    img = [[4] * 320 for _ in range(240)]        # blue

    def blit(e, dx, dy):
        for j in range(e['h']):
            for i in range(e['w']):
                v = sheet[e['y'] + j][e['x'] + i]
                if v != 8 and 0 <= dx + i < 320 and 0 <= dy + j < 240:
                    img[dy + j][dx + i] = v

    for n, e in enumerate(shown):
        blit(e, (n % 10) * 32, (n // 10) * 33)
    for fl in range(4):
        blit(flips[SPACEMAN + (fl,)], 8 + fl * 24, 200)
        blit(flips[IMP + (fl,)], 120 + fl * 24, 200)
    save_png(os.path.join(out, 'ref_objects.png'), 320, 240, img, palette=BBC_RGB + [(0, 100, 0)])

    prog = """' objview.bas - the object sprite sheet from flash slot 2, generated by test_objects.py
' Sixty sprites and the spaceman and an imp in all four orientations, over
' blue with the key colour transparent; saves exile_objview.bmp beside this
' program.  Slot 2 holds the tail of the tileset with the objects below it,
' because the third flash slot belongs to the library.
Option EXPLICIT
Option BASE 0
' the screen is for the sheet; what is printed goes to the serial console
Option CONSOLE SERIAL
Dim integer i, s, p, fl, x, y, w, h, n, lasts, total
Dim integer spx(3), spy(3), spw, sph, imx(3), imy(3), imw, imh
Dim homeDir$
homeDir$ = MM.Info(Path) : If homeDir$ = "NONE" Then homeDir$ = "A:/"
MODE 2
CLS
FRAMEBUFFER CREATE
Print "loading the slot 2 image (the tileset tail and the objects) ..."
Flash LOAD IMAGE 2, homeDir$ + "exile_slot2.bmp", O
FRAMEBUFFER WRITE F
Box 0, 0, 320, 240, 0, RGB(BLUE), RGB(BLUE)
Restore ObjectSheet
Read total
n = 0 : lasts = -1
For i = 1 To total
  Read s, p, fl, x, y, w, h
  If fl = 0 And s <> lasts And n < 60 Then
    Blit FLASH 2, F, x, y, (n Mod 10) * 32, (n \\ 10) * 33, w, h, 2
    n = n + 1 : lasts = s
  EndIf
  If s = %d And p = %d Then spx(fl) = x : spy(fl) = y : spw = w : sph = h
  If s = %d And p = %d Then imx(fl) = x : imy(fl) = y : imw = w : imh = h
Next i
For fl = 0 To 3
  Blit FLASH 2, F, spx(fl), spy(fl), 8 + fl * 24, 200, spw, sph, 2
  Blit FLASH 2, F, imx(fl), imy(fl), 120 + fl * 24, 200, imw, imh, 2
Next fl
FRAMEBUFFER COPY F, N
FRAMEBUFFER WRITE N
Save IMAGE homeDir$ + "exile_objview.bmp"
Print "objview: " + Str$(n) + " sprites drawn"
Option CONSOLE BOTH
End

""" % (SPACEMAN + IMP)
    prog += open(os.path.join(out, 'objects.bas')).read()
    dest = os.path.join(here, '..', 'exile', 'objview.bas')
    open(dest, 'w', newline='\r\n').write(prog)
    print("wrote", os.path.normpath(dest), "and out/ref_objects.png")


if __name__ == '__main__':
    sys.exit(main())
