"""Generate a library and a program big enough to prove the size claim.

One MMBasic program can be MAX_PROG_SIZE - 144 KB on this firmware.  A
program with a library behind it has that much again.  These two writers
fill each half with real, working code - subroutines that compute, and DATA
that is read back - so the test can check a number at the end rather than
just watching two big files load.

Sizes here are of the SOURCE.  LIBRARY SAVE and AUTOSAVE both crunch on the
way in (comments, blank lines and runs of spaces go), so what lands in flash
is smaller; the test reads the real figures back off the board with MEMORY.

One limit shapes the filler: funtbl, which holds every SUB, every FUNCTION
and every label, is MAXSUBFUN entries for the program and the library
together - 512 on this firmware.  So the bulk is made of a few long routines
rather than many short ones, which is what a real program looks like anyway.
"""

BODY = 30        # lines in a generated routine: long routines, few names

HEAD_LIB = """' Generated by gen_bulk.py - bulk filler for the library half.
' No END: the interpreter runs the whole library at RUN.
CONST BULKVER = 1
DIM INTEGER bulkReady
bulkReady = 1
"""

HEAD_PROG = """' Generated by gen_bulk.py - bulk filler for the program half.
DIM INTEGER bi, btotal, bexpect
"""


def write_library(path, target_bytes):
    """Subroutines and DATA until the source reaches target_bytes."""
    out = [HEAD_LIB]
    size = len(HEAD_LIB)
    nsub = 0
    ndata = 0
    # Alternate a function and a DATA block so both kinds of content are bulky.
    while size < target_bytes:
        if nsub <= ndata:
            nsub += 1
            body = []
            body.append("FUNCTION BulkF%d(v AS INTEGER) AS INTEGER" % nsub)
            body.append("  LOCAL INTEGER t")
            body.append("  t = v")
            for k in range(BODY):
                body.append("  t = t + %d : IF t > 100000 THEN t = t - 100000" % (k * 7 + nsub))
            body.append("  BulkF%d = t" % nsub)
            body.append("END FUNCTION")
            chunk = "\n".join(body) + "\n"
        else:
            ndata += 1
            body = ["dat_bulk%d:" % ndata]
            for row in range(20):
                body.append("DATA " + ",".join(str((ndata * 31 + row * 7 + c) % 1000) for c in range(16)))
            chunk = "\n".join(body) + "\n"
        out.append(chunk)
        size += len(chunk)
    open(path, "w", newline="\r\n").write("".join(out))
    return nsub, ndata


def write_program(path, target_bytes, nsub, ndata):
    """A program that calls into all of it, then pads itself out to size."""
    out = [HEAD_PROG]
    body = []
    body.append('PRINT "--- bulk ---"')
    body.append('PRINT "ready    "; bulkReady')
    body.append("btotal = 0")
    # call every generated function once
    for i in range(1, nsub + 1):
        body.append("btotal = btotal + BulkF%d(%d)" % (i, i))
    # read the first row of every generated DATA block
    for i in range(1, ndata + 1):
        body.append("RESTORE dat_bulk%d" % i)
        body.append("READ bi : btotal = btotal + bi")
    body.append('PRINT "subs     "; %d' % nsub)
    body.append('PRINT "data     "; %d' % ndata)
    body.append('PRINT "checksum "; btotal')
    body.append('PRINT "expected "; bexpect')
    body.append('PRINT "--- end ---"')
    body.append("END")
    core = "\n".join(body) + "\n"

    # Work out what the answer should be, on this side, so the board's figure
    # can be checked rather than merely printed.
    expect = 0
    for i in range(1, nsub + 1):
        t = i
        for k in range(BODY):
            t = t + (k * 7 + i)
            if t > 100000:
                t -= 100000
        expect += t
    for i in range(1, ndata + 1):
        expect += (i * 31) % 1000
    core = core.replace("PRINT \"expected \"; bexpect", "PRINT \"expected \"; %d" % expect)

    out.append(core)
    size = len("".join(out))
    # Pad with subroutines the program never calls: real lines, real cost.
    npad = 0
    while size < target_bytes:
        npad += 1
        pad = ["SUB PadS%d(v AS INTEGER)" % npad, "  LOCAL INTEGER t", "  t = v"]
        for k in range(BODY):
            pad.append("  t = t + %d : IF t > 100000 THEN t = t - 100000" % (k * 3 + npad))
        pad.append("END SUB")
        chunk = "\n".join(pad) + "\n"
        out.append(chunk)
        size += len(chunk)
    open(path, "w", newline="\r\n").write("".join(out))
    return npad


if __name__ == "__main__":
    import sys, os
    kb = int(sys.argv[1]) if len(sys.argv) > 1 else 110
    here = os.path.dirname(os.path.abspath(__file__))
    a = write_library(os.path.join(here, "biglib.bas"), kb * 1024)
    b = write_program(os.path.join(here, "bigmain.bas"), kb * 1024, *a)
    print("library: %d subs, %d data blocks" % a)
    print("program: %d padding subs" % b)
